//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ceenth.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preset
    {
        public int IdPreset { get; set; }
        public string Name { get; set; }
        public bool IsUserPreset { get; set; }
        public int Waveform { get; set; }
        public float AttackSeconds { get; set; }
        public float ReleaseSeconds { get; set; }
        public float FilterCutoff { get; set; }
        public float FilterQ { get; set; }
        public float VibratoRate { get; set; }
        public float VibratoDepth { get; set; }
        public float TremoloRate { get; set; }
        public float TremoloDepth { get; set; }
    }
}
